schema:
  format:
    openapi: "3.0.0"
  service_input_type: "LoadBalancedFargateServiceInput"
  types:
    LoadBalancedFargateServiceInput:
      type: object
      description: "Input properties for a loadbalanced Fargate service"
      properties:
        port:
          type: number
          title: "Container Port"
          description: "The port the container listens on"
          default: 8080
          minimum: 0
          maximum: 65535
        health_check_path:
          title: Health Check Path
          description: The health check path
          type: string
          default: /health
        desired_count:
          type: number
          title: "Desired Task Count"
          description: "The default number of Fargate tasks you want running"
          default: 1
          minimum: 1
        task_size:
          type: string
          title: "Task Size (CPU/Memory)"
          description: "The size of the task you want to run"
          enum: ["x-small", "small", "medium", "large", "x-large"]
          default: "x-small"
        subnet_type:
          type: string
          title: "Subnet location"
          description: "Which subnet to run tasks in"
          enum: ["public", "private"]
          default: "private"
        image:
          type: string
          title: "Container Image"
          description: "The container image to deploy"
          default: "public.ecr.aws/aws-containers/proton-demo-image:1e5ca1d"
          minLength: 1
          maxLength: 200
